### ISSUE TITLE
Following the setup instructions gives a SystemStackError

### ISSUE THREAD

**Issue by plainlystated** [assaf/vanity#297] opened 2016-05-18 03:05 UTC
After downloading the latest version of the gem, I went through the instructions in the README, using my existing postgresql DB as the datastore. When I get to the step of generating the report, I get an exception:

```
$ vanity report
W, [2016-05-17T22:01:16.369563 #11417]  WARN -- : No default alternative specified; choosing black as default.
/home/patrick/.rvm/gems/ruby-2.2.1@workbench/gems/actionpack-4.2.0/lib/action_dispatch/testing/test_process.rb:18:in `flash': stack level too deep (SystemStackError)
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/gems/actionpack-4.2.0/lib/action_dispatch/testing/test_process.rb:18:in `flash'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/gems/actionpack-4.2.0/lib/action_dispatch/testing/test_process.rb:18:in `flash'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/gems/actionpack-4.2.0/lib/action_dispatch/testing/test_process.rb:18:in `flash'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/gems/actionpack-4.2.0/lib/action_dispatch/testing/test_process.rb:18:in `flash'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/gems/actionpack-4.2.0/lib/action_dispatch/testing/test_process.rb:18:in `flash'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/gems/actionpack-4.2.0/lib/action_dispatch/testing/test_process.rb:18:in `flash'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/gems/actionpack-4.2.0/lib/action_dispatch/testing/test_process.rb:18:in `flash'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/gems/actionpack-4.2.0/lib/action_dispatch/testing/test_process.rb:18:in `flash'
         ... 10063 levels...
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/bin/vanity:23:in `load'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/bin/vanity:23:in `<main>'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/bin/ruby_executable_hooks:15:in `eval'
        from /home/patrick/.rvm/gems/ruby-2.2.1@workbench/bin/ruby_executable_hooks:15:in `<main>'
```

I believe the only way I deviated from the example was in the metric & test I defined:

```
patrick@patrick-x1-lcp:~/repos/work/workbench$ find experiments/
experiments/
experiments/headline_color.rb
experiments/metrics
experiments/metrics/view_article.rb

patrick@patrick-x1-lcp:~/repos/work/workbench$ cat experiments/headline_color.rb 
ab_test "Headline color" do
  description "Test the color of a headline"
  alternatives "black", "green", "red"
  metrics :view_article
end

patrick@patrick-x1-lcp:~/repos/work/workbench$ cat experiments/metrics/view_article.rb 
metric "View an article" do
  description "View an article"
end
```

**Comment by plainlystated** [comment] 2016-05-18 03:11
FWIW, I am able to view the report using a rails controller. It's only the CLI report that raises this exception for me.

**Comment by phillbaker** [comment] 2016-05-20 12:23
Thanks @plainlystated, will take a look.

**Comment by phillbaker** [comment] 2016-06-06 03:30
@plainlystated, can you confirm the version of the gem you have installed? This looks similar to https://github.com/assaf/vanity/issues/105 or https://github.com/assaf/vanity/pull/239.

**Comment by phillbaker** [comment] 2016-10-06 11:49
I can't reproduce this on master of vanity using ruby 2.2.2 or 2.1.5. Going to close this, but please reopen if there's more information.

**Closed by phillbaker** 2016-10-06 11:49 UTC
